# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewCSTest():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_newCSTest(self):
    # Test name: newCSTest
    # Step # | name | target | value
    # 1 | open | http://test.crowdstreet.com | 
    self.driver.get("http://test.crowdstreet.com")
    # 2 | click | css=.tablet-menu > .join-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".tablet-menu > .join-button").click()
    # 3 | type | id=firstName | AUTOMATED
    self.driver.find_element(By.ID, "firstName").send_keys("AUTOMATED")
    # 4 | type | id=lastName | TEST
    self.driver.find_element(By.ID, "lastName").send_keys("TEST")
    # 5 | type | id=email | amaxj95@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("email@email.com")
    # 6 | type | id=password | db!ppQer5TTtA56
    self.driver.find_element(By.ID, "password").send_keys("db!ppQer5TTtA56")
    # 7 | type | id=confirmPassword | db!ppQer5TTtA56
    self.driver.find_element(By.ID, "confirmPassword").send_keys("db!ppQer5TTtA56")
    # 8 | click | id=accreditedYes | 
    self.driver.find_element(By.ID, "accreditedYes").click()
    # 9 | click | id=hasAgreedTos | 
    self.driver.find_element(By.ID, "hasAgreedTos").click()
    # 10 | click | css=.h-14 | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-14").click()
    # 11 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 12 | close |  | 
    self.driver.close()
  
